- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: Update repositories cache and install "yarn" package
  apt:
    name: yarn
    update_cache: yes
