---

- include: 00-git.yml
- include: 10-yarn.yml


- name: Give permissions
  shell: |
    chown -R ubuntu:ubuntu {{ project_root }}

- name: Install packages
  shell: |
    sudo apt-get install libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0

- name: Install packages and run build
  shell: |
    cd {{ project_root }}
    yarn install
    yarn build

