---

- include: 00-git.yml

- name: install packages
  shell: |
    cd {{ project_root }}
    npm install
    npm run build

- name: starting project
  shell: |
    cd {{ project_root }}
    npm install -g serve
    serve -s build
