---

- include: 00-git.yml
- include: 10-yarn.yml


- name: Give permissions
  shell: |
    chown -R ubuntu:ubuntu {{ project_root }}

- name: Install packages and run build
  shell: |
    cd {{ project_root }}
    yarn install
    yarn build

