---

- include: 00-git.yml
- include: 10-yarn.yml

- name: isntall pm2
  shell: |
    sudo npm install pm2@latest -g

- name: install packages
  shell: |
    cd {{ project_root }}
    sudo yarn install
    sudo npm run build

- name: starting project
  shell: |
    cd {{ project_root }}
    pm2 start server/index.js
