---

- include: 00-git.yml
- include: 10-yarn.yml

- name: Install pm2
  npm:
    name: pm2
    global: yes

- name: Install packages and run build
  shell: |
    cd {{ project_root }}
    yarn install
    npm run build
  become: true

- name: Starting project
  shell: |
    cd {{ project_root }}
    pm2 start server/index.js
